version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
  build:
    commands:
      # look at this if there is docker deamon error when building docker imagehttps://docs.aws.amazon.com/codebuild/latest/userguide/troubleshooting.html#troubleshooting-cannot-connect-to-docker-daemon
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t rwijupal3058/mythicalmisfits:v1 ./app
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push rwijupal3058/mythicalmisfits:v1
