version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
  build:
    commands:
      # look at this if there is docker deamon error when building docker imagehttps://docs.aws.amazon.com/codebuild/latest/userguide/troubleshooting.html#troubleshooting-cannot-connect-to-docker-daemon
      #  make sure the CodeBuild runs in priveldged mode (look at Envirement -> Overide Image -> Priveldged)
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t rwijupal3058/mythicalmisfits:latest ./app
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push rwijupal3058/mythicalmisfits:latest
      - echo Completed pushing Docker image. Deploying Docker image to AWS Fargate on `date`
      # Create a artifacts file that contains the name and location of the image
      # pushed to ECR. This will be used by AWS CodePipeline to automate
      # deployment of this specific container to Amazon ECS.
      # NOTE: make sure the "name" below is that of CONTAINER NAME available in TASK DEFINITION JSON in ECS
      - printf '[{"ImageURI":"rwijupal3058/mythicalmisfits:latest"}]' > imageDetail.json       

# Blue Green Deployment
artifacts:
# Defining the files that need to converted to an artifact
  files: 
    - 'imageDetail.json'
    - 'appspec.yaml'
    - 'taskdef.json'
# Actual artifactst that will be created
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json    